language: node_js
node_js:
- node
dist: xenial
cache:
- npm
script: npm run build
deploy:
  local_dir: build
  target_branch: gh-pages
  fqdn: matkalasku.matematiikkakilpailut.fi
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  verbose: true
